app = "vedhanth"
primary_region = "bom"  # Change this to your preferred region

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health/"

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static"

[[statics]]
  guest_path = "/app/data/media"
  url_prefix = "/media"

[[mounts]]
  source="portfolio_data"
  destination="/app/data"

[env]
